#pragma once
#include "Types.hpp"

using namespace std;

namespace Engine
{
    struct OrderRequest // The struct obtained directly from the client
    {
        uint64_t clientId;
        uint64_t clientOrderId;
        uint64_t price;
        uint64_t quantity;
        OrderType type;
        Side side;
    };

    // The struct created by the matching engine and then stored in the order book
    struct OrderTypes {
        uint64_t  id;    // Globally unique OrderId generated by the exchange
        uint64_t  client_id;
        uint64_t  client_order_id;  // Sent by the client; Used for cancel / modify orders
        Side      side;
        OrderType type;

        uint64_t  price;
        uint64_t  quantity;       // original submitted quantity
        uint64_t  remaining;      // quantity still open (decremented on fills)

        uint64_t  timestamp;      // wall-clock ns, for logging only
        OrderTypes* next_; // Used by order pool
        OrderTypes* next_in_list ;  // Used by ask and bid maps
        OrderTypes* prev_in_list ;  // Used by the ask and bid maps

        [[nodiscard]] bool is_buy() const noexcept { return side == Side::BUY; }
        [[nodiscard]] bool is_filled() const noexcept { return remaining <= 0; }
    };

    // The request received from client along with the globally unique order ID
    // MPSC queue
    struct Command {
        uint64_t order_id{};  // Globally unique order ID
        OrderRequest request{};
        uint64_t enqueue_ns{0}; // Used to calculate latency
    };

    // Status of the order after immediate matching once received
    enum class OrderStatus : uint8_t
    {
        FILLED = 1,
        CANCELLED = 2,
        RESTING = 3,
        MODIFIED = 4,
        UNKNOWN = 5
    };

    // Top of the order book data used while logging market data
    struct MarketData {
        bool has_bid{false};
        bool has_ask{false};
        uint64_t ask_price{0};
        uint64_t bid_price{0};
        uint64_t ask_quantity{0};
        uint64_t bid_quantity{0};
    };
}