#pragma once

#include <engine/Types.hpp>
#include <string>

using namespace std;

namespace Engine
{
    struct OrderRequest // The struct obtained directly from the client
    {
        uint64_t clientId;
        uint64_t clientOrderId;
        uint64_t price;
        uint64_t quantity;
        OrderType type;
        Side side;
    };

    // The struct created by the matching engine and then stored in the order book
    struct Order {
        uint64_t  id;    // Globally unique OrderId generated by the exchange
        uint64_t  client_id;
        uint64_t  client_order_id;  // Sent by the client; Used for cancel / modify orders
        Side      side;
        OrderType type;

        uint64_t  price;
        uint64_t  quantity;       // original submitted quantity
        uint64_t  remaining;      // quantity still open (decremented on fills)

        uint64_t  timestamp;      // wall-clock ns, for logging only
        Order* next_; // Used by order pool
        Order* next_in_list ;  // Used by ask and bid maps
        Order* prev_in_list ;  // Used by the ask and bid maps

        [[nodiscard]] bool is_buy() const noexcept { return side == Side::BUY; }
        [[nodiscard]] bool is_filled() const noexcept { return remaining <= 0; }
};

}